### ISSUE TITLE
Date range not reported

### ISSUE THREAD

**Issue by IanGrimstead** [datasciencecampus/pyGrams#31]
**Describe the bug**
When -yf or -yt used, date range always reported as 'None'

**To Reproduce**
1. python detect.py -yf 2000 -yt 2018
2. Observe output:
```
Patents readied; 1,000 patents loaded
1,000 patents available after publication date sift
Dropped 0 patents due to empty abstracts
In date range None to None there are 1,000 patents
1. power supply                   3.332515  
...
```

**Expected behavior**
Output should be:
```
Patents readied; 1,000 patents loaded
1,000 patents available after publication date sift
Dropped 0 patents due to empty abstracts
In date range 2000-01-01 to 2018-12-31 there are 1,000 patents
1. power supply                   3.332515  
...
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: N/A
 - Version: 10.13.6

**Comment by IanGrimstead** [comment]
Raised branch 31-date-reporting

**Comment by mshodge** [comment]
Issue still persists.

**Describe the bug**
When -yf or -yt used, date range is not passed into TFIDF calculation.

**To Reproduce**
Steps to reproduce the behavior:

python detect.py -yt 2016

Observe output:
Dropped 0 patents due to empty abstracts
Processing TFIDF of 1,000 documents
No focus applied
1. semiconductor substrate        2.552598
...

**Expected behavior**
Output should be:

Sifting documents between 01-Jan-2000 and 31-Dec-2016
864 documents available after publication date sift
Dropped 0 patents due to empty abstracts
Processing TFIDF of 864 documents
No focus applied
1. semiconductor substrate        2.534450
...
Screenshots
N/A

Desktop (please complete the following information):

OS: MacOS
Browser: N/A
Version: 10.12.2
